export default [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly'
      }
    },
    rules: {
      'no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }],
      'no-console': 'off',
      'prefer-const': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-arrow-callback': 'error',
      'arrow-spacing': 'error',
      'eqeqeq': ['error', 'always'],
      'curly': ['error', 'all'],
      'brace-style': ['error', '1tbs'],
      'comma-dangle': ['error', 'never'],
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'indent': ['error', 2],
      'linebreak-style': ['error', 'unix'],
      'max-len': ['error', { 'code': 100, 'ignoreUrls': true, 'ignoreStrings': true }],
      'no-trailing-spaces': 'error',
      'eol-last': 'error'
    },
    ignores: [
      'node_modules/',
      'coverage/',
      'playwright-report/',
      'test-results/',
      'tmp/',
      'logs/',
      'public/',
      'docs/api/',
      'BestPractices/',
      'KnowledgeTransferTest/',
      'Property Booking System/',
      'kt-cli-alpha/',
      'demos/',
      'data/',
      'reports/',
      'sandbox/',
      'utils/',
      'scripts/',
      'servers/',
      'test-data/',
      '*.config.js',
      '*.config.mjs',
      'jest.config.js',
      'playwright.config.js'
    ]
  }
];